-- duogreen: green and grey on true black. Code content is pure green (hue
-- 120) at three brightnesses; everything secondary is a grey ramp. No white.
-- High-contrast accents appear only to get your attention; syntax itself
-- never uses them:
--   red     errors, diff removals, replace mode, breakpoints
--   orange  warnings, values the debugger saw change
--   yellow  NOTE/TODO in comments, the matching bracket
--   cyan    info diagnostics, hop jump labels, where the debugger is stopped
--
-- Tone map for code:
--   g0        functions, constructors, macros, matches, emphasis
--   g1 bold   keywords, control flow
--   g1        identifiers, variables, properties (main text)
--   g2        strings, numbers, booleans, nullptr
--   gray4     types, namespaces, preprocessor, operators
--   gray3     punctuation, comments (italic)
--   gray2-0   line numbers, borders, whitespace markers

local M = {}

M.palette = {
  black = '#000000',
  bg1 = '#0a0a0a', -- floats, pickers
  bg2 = '#121212', -- cursorline, colorcolumn
  bg3 = '#1c1c1c', -- quickfix line, button, references
  bg4 = '#262626', -- visual, pmenu selection
  bg_hi = '#003a00', -- search, diff add background
  g0 = '#00ff00',
  g1 = '#00d400',
  g2 = '#00a800',
  gray4 = '#8c8c8c',
  gray3 = '#666666',
  gray2 = '#474747',
  gray1 = '#333333',
  gray0 = '#262626',
  red = '#e06c75',
  red_dim = '#9e5560',
  red_bg = '#2a1012',
  yellow = '#e0c070',
  yellow_dim = '#9c8a52',
  orange = '#f5a25d',
  orange_dim = '#a8713f',
  cyan = '#4fd6e0',
  cyan_dim = '#3a8a90',
}

function M.lualine()
  local p = M.palette
  local function mode(a)
    return {
      a = a,
      b = { fg = p.g2, bg = p.black },
      c = { fg = p.gray4, bg = p.black },
    }
  end
  return {
    normal = mode({ fg = p.g0, bg = p.black, gui = 'bold' }),
    insert = mode({ fg = p.black, bg = p.g0, gui = 'bold' }),
    visual = mode({ fg = p.black, bg = p.g2, gui = 'bold' }),
    replace = mode({ fg = p.black, bg = p.red, gui = 'bold' }),
    command = mode({ fg = p.g2, bg = p.black, gui = 'bold' }),
    terminal = mode({ fg = p.black, bg = p.g0, gui = 'bold' }),
    inactive = {
      a = { fg = p.gray2, bg = p.black },
      b = { fg = p.gray2, bg = p.black },
      c = { fg = p.gray2, bg = p.black },
    },
  }
end

function M.load()
  local p = M.palette
  vim.cmd('highlight clear')
  if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
  vim.o.termguicolors = true
  vim.o.background = 'dark'
  vim.g.colors_name = 'duogreen'

  local groups = {
    -- Editor chrome
    Normal = { fg = p.g1, bg = p.black },
    NormalNC = { link = 'Normal' },
    NormalFloat = { fg = p.g1, bg = p.bg1 },
    FloatBorder = { fg = p.gray1, bg = p.bg1 },
    FloatTitle = { fg = p.g0, bg = p.bg1, bold = true },
    FloatFooter = { fg = p.gray3, bg = p.bg1 },
    Cursor = { reverse = true },
    lCursor = { link = 'Cursor' },
    TermCursor = { reverse = true },
    TermCursorNC = { bg = p.gray2 },
    CursorLine = { bg = p.bg2 },
    CursorColumn = { bg = p.bg2 },
    ColorColumn = { bg = p.bg2 },
    CursorLineNr = { fg = p.g0, bold = true },
    LineNr = { fg = p.gray2 },
    LineNrAbove = { link = 'LineNr' },
    LineNrBelow = { link = 'LineNr' },
    SignColumn = { fg = p.gray2 },
    FoldColumn = { fg = p.gray2 },
    Folded = { fg = p.gray3, bg = p.bg2 },
    WinSeparator = { fg = p.gray0 },
    VertSplit = { link = 'WinSeparator' },
    EndOfBuffer = { fg = p.black },
    NonText = { fg = p.gray0 },
    Whitespace = { fg = p.gray0 },
    SpecialKey = { fg = p.gray0 },
    Conceal = { fg = p.gray3 },
    Visual = { bg = p.bg4 },
    VisualNOS = { link = 'Visual' },
    Search = { fg = p.g0, bg = p.bg_hi },
    CurSearch = { fg = p.black, bg = p.g0, bold = true },
    IncSearch = { link = 'CurSearch' },
    Substitute = { link = 'CurSearch' },
    MatchParen = { fg = p.yellow, bg = p.bg4, bold = true },
    Pmenu = { fg = p.g1, bg = p.bg1 },
    PmenuSel = { fg = p.g0, bg = p.bg4, bold = true },
    PmenuKind = { fg = p.gray3, bg = p.bg1 },
    PmenuKindSel = { fg = p.gray4, bg = p.bg4 },
    PmenuExtra = { fg = p.gray3, bg = p.bg1 },
    PmenuExtraSel = { fg = p.gray4, bg = p.bg4 },
    PmenuSbar = { bg = p.bg3 },
    PmenuThumb = { bg = p.gray1 },
    WildMenu = { link = 'PmenuSel' },
    StatusLine = { fg = p.gray4, bg = p.bg1 },
    StatusLineNC = { fg = p.gray2, bg = p.bg1 },
    StatusLineTerm = { link = 'StatusLine' },
    StatusLineTermNC = { link = 'StatusLineNC' },
    TabLine = { fg = p.gray3, bg = p.bg1 },
    TabLineSel = { fg = p.g0, bg = p.black, bold = true },
    TabLineFill = { bg = p.bg1 },
    WinBar = { fg = p.gray4 },
    WinBarNC = { fg = p.gray2 },
    MsgArea = { fg = p.g1 },
    MsgSeparator = { bg = p.gray0 },
    ModeMsg = { fg = p.gray4 },
    MoreMsg = { fg = p.g0 },
    Question = { fg = p.g0 },
    WarningMsg = { fg = p.yellow },
    ErrorMsg = { fg = p.red },
    Title = { fg = p.g0, bold = true },
    Directory = { fg = p.g0 },
    QuickFixLine = { bg = p.bg3 },
    qfLineNr = { fg = p.gray2 },
    qfFileName = { fg = p.g0 },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.yellow, undercurl = true },
    SpellLocal = { sp = p.gray3, undercurl = true },
    SpellRare = { sp = p.gray3, undercurl = true },
    healthSuccess = { fg = p.g0 },
    healthWarning = { fg = p.orange },
    healthError = { fg = p.red },

    -- Diff
    DiffAdd = { bg = p.bg_hi },
    DiffDelete = { fg = p.gray1, bg = p.red_bg },
    DiffChange = { bg = p.bg2 },
    DiffText = { bg = p.bg4 },
    Added = { fg = p.g0 },
    Removed = { fg = p.red },
    Changed = { fg = p.gray4 },
    diffAdded = { link = 'Added' },
    diffRemoved = { link = 'Removed' },
    diffChanged = { link = 'Changed' },
    diffLine = { fg = p.gray4 },
    diffFile = { fg = p.gray4, bold = true },
    diffIndexLine = { fg = p.gray3 },
    diffOldFile = { fg = p.red_dim },
    diffNewFile = { fg = p.g2 },

    -- Syntax (legacy groups)
    Comment = { fg = p.gray3, italic = true },
    Constant = { fg = p.g1 },
    String = { fg = p.g2 },
    Character = { link = 'String' },
    Number = { fg = p.g2 },
    Float = { link = 'Number' },
    Boolean = { fg = p.g2 },
    Identifier = { fg = p.g1 },
    Function = { fg = p.g0 },
    Statement = { fg = p.g1, bold = true },
    Keyword = { link = 'Statement' },
    Conditional = { link = 'Statement' },
    Repeat = { link = 'Statement' },
    Label = { fg = p.gray4 },
    Exception = { link = 'Statement' },
    Operator = { fg = p.gray4 },
    PreProc = { fg = p.gray4 },
    Include = { link = 'PreProc' },
    Define = { link = 'PreProc' },
    Macro = { fg = p.g0 },
    PreCondit = { link = 'PreProc' },
    Type = { fg = p.gray4 },
    StorageClass = { link = 'Statement' },
    Structure = { link = 'Statement' },
    Typedef = { link = 'Statement' },
    Special = { fg = p.g0 },
    SpecialChar = { link = 'Special' },
    Tag = { fg = p.g0 },
    Delimiter = { fg = p.gray3 },
    SpecialComment = { fg = p.gray4, italic = true },
    Debug = { fg = p.gray4 },
    Underlined = { underline = true },
    Ignore = { fg = p.gray1 },
    Error = { fg = p.red },
    Todo = { fg = p.yellow, bold = true },

    -- Tree-sitter
    ['@variable'] = { fg = p.g1 },
    ['@variable.builtin'] = { fg = p.gray4, italic = true },
    ['@variable.parameter'] = { fg = p.g1, italic = true },
    ['@variable.parameter.builtin'] = { fg = p.gray4, italic = true },
    ['@variable.member'] = { fg = p.g1 },
    ['@property'] = { fg = p.g1 },
    ['@constant'] = { fg = p.g1 },
    ['@constant.builtin'] = { fg = p.g2 },
    ['@constant.macro'] = { fg = p.gray4 },
    ['@module'] = { fg = p.gray4 },
    ['@module.builtin'] = { fg = p.gray4 },
    ['@label'] = { fg = p.gray4 },
    ['@string'] = { link = 'String' },
    ['@string.documentation'] = { link = 'Comment' },
    ['@string.regexp'] = { fg = p.g0 },
    ['@string.escape'] = { fg = p.g0 },
    ['@string.special'] = { fg = p.g0 },
    ['@string.special.symbol'] = { fg = p.g1 },
    ['@string.special.path'] = { fg = p.g2 },
    ['@string.special.url'] = { fg = p.g2, underline = true },
    ['@character'] = { link = 'String' },
    ['@character.special'] = { fg = p.g0 },
    ['@boolean'] = { link = 'Boolean' },
    ['@number'] = { link = 'Number' },
    ['@number.float'] = { link = 'Number' },
    ['@type'] = { fg = p.gray4 },
    ['@type.builtin'] = { fg = p.gray4 },
    ['@type.definition'] = { fg = p.gray4 },
    ['@attribute'] = { fg = p.gray4, italic = true },
    ['@attribute.builtin'] = { fg = p.gray4, italic = true },
    ['@function'] = { fg = p.g0 },
    ['@function.builtin'] = { fg = p.g0 },
    ['@function.call'] = { fg = p.g0 },
    ['@function.macro'] = { fg = p.g0 },
    ['@function.method'] = { fg = p.g0 },
    ['@function.method.call'] = { fg = p.g0 },
    ['@constructor'] = { fg = p.g0 },
    ['@operator'] = { fg = p.gray4 },
    ['@keyword'] = { fg = p.g1, bold = true },
    ['@keyword.coroutine'] = { link = '@keyword' },
    ['@keyword.function'] = { link = '@keyword' },
    ['@keyword.operator'] = { fg = p.gray4 },
    ['@keyword.import'] = { fg = p.gray4 },
    ['@keyword.type'] = { link = '@keyword' },
    ['@keyword.modifier'] = { link = '@keyword' },
    ['@keyword.repeat'] = { link = '@keyword' },
    ['@keyword.return'] = { link = '@keyword' },
    ['@keyword.debug'] = { fg = p.gray4 },
    ['@keyword.exception'] = { link = '@keyword' },
    ['@keyword.conditional'] = { link = '@keyword' },
    ['@keyword.conditional.ternary'] = { fg = p.gray4 },
    ['@keyword.directive'] = { fg = p.gray4 },
    ['@keyword.directive.define'] = { fg = p.gray4 },
    ['@punctuation.delimiter'] = { fg = p.gray3 },
    ['@punctuation.bracket'] = { fg = p.gray3 },
    ['@punctuation.special'] = { fg = p.g0 },
    ['@comment'] = { link = 'Comment' },
    ['@comment.documentation'] = { link = 'Comment' },
    ['@comment.error'] = { fg = p.red, bold = true },
    ['@comment.warning'] = { fg = p.orange, bold = true },
    ['@comment.todo'] = { fg = p.yellow, bold = true },
    ['@comment.note'] = { fg = p.yellow, bold = true },
    ['@markup.strong'] = { bold = true },
    ['@markup.italic'] = { italic = true },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.underline'] = { underline = true },
    ['@markup.heading'] = { fg = p.g0, bold = true },
    ['@markup.heading.1'] = { fg = p.g0, bold = true },
    ['@markup.heading.2'] = { fg = p.g0, bold = true },
    ['@markup.heading.3'] = { fg = p.g2, bold = true },
    ['@markup.heading.4'] = { fg = p.g2, bold = true },
    ['@markup.heading.5'] = { fg = p.gray4, bold = true },
    ['@markup.heading.6'] = { fg = p.gray4, bold = true },
    ['@markup.quote'] = { fg = p.gray3, italic = true },
    ['@markup.math'] = { fg = p.gray4 },
    ['@markup.link'] = { fg = p.g0 },
    ['@markup.link.label'] = { fg = p.g0 },
    ['@markup.link.url'] = { fg = p.g2, underline = true },
    ['@markup.raw'] = { fg = p.gray4 },
    ['@markup.raw.block'] = { fg = p.gray4 },
    ['@markup.list'] = { fg = p.gray3 },
    ['@markup.list.checked'] = { fg = p.g0 },
    ['@markup.list.unchecked'] = { fg = p.gray3 },
    ['@diff.plus'] = { link = 'Added' },
    ['@diff.minus'] = { link = 'Removed' },
    ['@diff.delta'] = { link = 'Changed' },
    ['@tag'] = { fg = p.g0 },
    ['@tag.builtin'] = { fg = p.g0 },
    ['@tag.attribute'] = { fg = p.gray4 },
    ['@tag.delimiter'] = { fg = p.gray3 },

    -- LSP semantic tokens: follow the tree-sitter tones.
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.struct'] = { link = '@type' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.interface'] = { link = '@type' },
    ['@lsp.type.typeParameter'] = { link = '@type' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.namespace'] = { link = '@module' },
    ['@lsp.type.function'] = { link = '@function' },
    ['@lsp.type.method'] = { link = '@function.method' },
    ['@lsp.type.macro'] = { link = '@function.macro' },
    ['@lsp.type.variable'] = { link = '@variable' },
    ['@lsp.type.parameter'] = { link = '@variable.parameter' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.keyword'] = { link = '@keyword' },
    ['@lsp.type.modifier'] = { link = '@keyword' },
    ['@lsp.type.operator'] = { link = '@operator' },
    ['@lsp.type.comment'] = { link = '@comment' },
    ['@lsp.type.string'] = { link = '@string' },
    ['@lsp.type.number'] = { link = '@number' },
    ['@lsp.type.decorator'] = { link = '@attribute' },
    ['@lsp.mod.deprecated'] = { strikethrough = true },
    ['@lsp.typemod.variable.readonly'] = { fg = p.g1 },
    ['@lsp.typemod.variable.defaultLibrary'] = { fg = p.gray4 },
    ['@lsp.typemod.function.defaultLibrary'] = { fg = p.g0 },

    -- Diagnostics
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.orange },
    DiagnosticInfo = { fg = p.cyan },
    DiagnosticHint = { fg = p.gray3 },
    DiagnosticOk = { fg = p.g0 },
    DiagnosticVirtualTextError = { fg = p.red_dim, italic = true },
    DiagnosticVirtualTextWarn = { fg = p.orange_dim, italic = true },
    DiagnosticVirtualTextInfo = { fg = p.cyan_dim, italic = true },
    DiagnosticVirtualTextHint = { fg = p.gray2, italic = true },
    DiagnosticVirtualTextOk = { fg = p.gray3, italic = true },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.cyan, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.gray2, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.g0, undercurl = true },
    DiagnosticFloatingError = { link = 'DiagnosticError' },
    DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
    DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
    DiagnosticFloatingHint = { link = 'DiagnosticHint' },
    DiagnosticSignError = { link = 'DiagnosticError' },
    DiagnosticSignWarn = { link = 'DiagnosticWarn' },
    DiagnosticSignInfo = { link = 'DiagnosticInfo' },
    DiagnosticSignHint = { link = 'DiagnosticHint' },
    DiagnosticUnnecessary = { fg = p.gray2 },
    DiagnosticDeprecated = { strikethrough = true, sp = p.gray3 },

    -- LSP
    LspReferenceText = { bg = p.bg3 },
    LspReferenceRead = { bg = p.bg3 },
    LspReferenceWrite = { bg = p.bg3, underline = true },
    LspReferenceTarget = { bg = p.bg3 },
    LspInlayHint = { fg = p.gray2, italic = true },
    LspCodeLens = { fg = p.gray2, italic = true },
    LspCodeLensSeparator = { fg = p.gray1 },
    LspSignatureActiveParameter = { fg = p.g0, bold = true },

    -- Telescope
    TelescopeNormal = { fg = p.g1, bg = p.bg1 },
    TelescopeBorder = { fg = p.gray1, bg = p.bg1 },
    TelescopeTitle = { fg = p.gray4, bg = p.bg1, bold = true },
    TelescopePromptNormal = { fg = p.g1, bg = p.bg3 },
    TelescopePromptBorder = { fg = p.gray1, bg = p.bg3 },
    TelescopePromptPrefix = { fg = p.g0, bg = p.bg3 },
    TelescopePromptCounter = { fg = p.gray3, bg = p.bg3 },
    TelescopePromptTitle = { fg = p.black, bg = p.g0, bold = true },
    TelescopeResultsTitle = { fg = p.gray3, bg = p.bg1 },
    TelescopePreviewTitle = { fg = p.gray3, bg = p.bg1 },
    TelescopeSelection = { fg = p.g0, bg = p.bg4 },
    TelescopeSelectionCaret = { fg = p.g0, bg = p.bg4 },
    TelescopeMultiSelection = { fg = p.g2, bg = p.bg1 },
    TelescopeMatching = { fg = p.g0, bold = true },
    TelescopeResultsComment = { fg = p.gray2 },
    TelescopeResultsDiffAdd = { fg = p.g0 },
    TelescopeResultsDiffChange = { fg = p.gray4 },
    TelescopeResultsDiffDelete = { fg = p.red },
    TelescopePreviewLine = { bg = p.bg3 },
    TelescopePreviewMatch = { link = 'Search' },

    -- blink.cmp
    BlinkCmpMenu = { link = 'Pmenu' },
    BlinkCmpMenuBorder = { link = 'FloatBorder' },
    BlinkCmpMenuSelection = { link = 'PmenuSel' },
    BlinkCmpScrollBarThumb = { link = 'PmenuThumb' },
    BlinkCmpScrollBarGutter = { link = 'PmenuSbar' },
    BlinkCmpLabel = { fg = p.g1 },
    BlinkCmpLabelMatch = { fg = p.g0, bold = true },
    BlinkCmpLabelDeprecated = { fg = p.gray2, strikethrough = true },
    BlinkCmpLabelDescription = { fg = p.gray3 },
    BlinkCmpLabelDetail = { fg = p.gray3 },
    BlinkCmpKind = { fg = p.gray3 },
    BlinkCmpSource = { fg = p.gray2 },
    BlinkCmpGhostText = { fg = p.gray2, italic = true },
    BlinkCmpDoc = { link = 'NormalFloat' },
    BlinkCmpDocBorder = { link = 'FloatBorder' },
    BlinkCmpDocSeparator = { link = 'FloatBorder' },
    BlinkCmpDocCursorLine = { link = 'CursorLine' },
    BlinkCmpSignatureHelp = { link = 'NormalFloat' },
    BlinkCmpSignatureHelpBorder = { link = 'FloatBorder' },
    BlinkCmpSignatureHelpActiveParameter = { link = 'LspSignatureActiveParameter' },

    -- Copilot
    CopilotSuggestion = { fg = p.gray2, italic = true },
    CopilotAnnotation = { fg = p.gray2, italic = true },

    -- gitsigns
    GitSignsAdd = { fg = p.g2 },
    GitSignsChange = { fg = p.gray4 },
    GitSignsDelete = { fg = p.red_dim },
    GitSignsTopdelete = { fg = p.red_dim },
    GitSignsChangedelete = { fg = p.gray4 },
    GitSignsUntracked = { fg = p.gray3 },
    GitSignsAddNr = { link = 'GitSignsAdd' },
    GitSignsChangeNr = { link = 'GitSignsChange' },
    GitSignsDeleteNr = { link = 'GitSignsDelete' },
    GitSignsAddLn = { bg = p.bg_hi },
    GitSignsChangeLn = { bg = p.bg2 },
    GitSignsAddInline = { bg = p.bg_hi },
    GitSignsChangeInline = { bg = p.bg4 },
    GitSignsDeleteInline = { bg = p.red_bg },
    GitSignsAddPreview = { bg = p.bg_hi },
    GitSignsDeletePreview = { bg = p.red_bg },
    GitSignsCurrentLineBlame = { fg = p.gray2, italic = true },
    GitSignsDeleteVirtLn = { fg = p.gray3, bg = p.red_bg },

    -- fugitive
    fugitiveHeader = { fg = p.g0, bold = true },
    fugitiveHeading = { fg = p.gray4, bold = true },
    fugitiveHelpHeader = { fg = p.gray4 },
    fugitiveSymbolicRef = { fg = p.g0 },
    fugitiveHash = { fg = p.gray3 },
    fugitiveCount = { fg = p.gray3 },
    fugitiveUntrackedHeading = { link = 'fugitiveHeading' },
    fugitiveUnstagedHeading = { link = 'fugitiveHeading' },
    fugitiveStagedHeading = { link = 'fugitiveHeading' },
    fugitiveUntrackedModifier = { fg = p.gray3 },
    fugitiveUnstagedModifier = { fg = p.gray3 },
    fugitiveStagedModifier = { fg = p.g2 },

    -- indent-blankline
    IblIndent = { fg = '#1a1a1a' },
    IblWhitespace = { fg = '#1a1a1a' },
    IblScope = { fg = p.gray1 },

    -- which-key
    WhichKey = { fg = p.g0 },
    WhichKeyGroup = { fg = p.gray4 },
    WhichKeyDesc = { fg = p.g1 },
    WhichKeySeparator = { fg = p.gray2 },
    WhichKeyNormal = { link = 'NormalFloat' },
    WhichKeyBorder = { link = 'FloatBorder' },
    WhichKeyTitle = { fg = p.g0, bold = true },
    WhichKeyValue = { fg = p.gray3 },
    WhichKeyIcon = { fg = p.gray3 },

    -- fidget
    FidgetTitle = { fg = p.g0 },
    FidgetTask = { fg = p.gray3 },

    -- hop
    HopNextKey = { fg = p.cyan, bold = true },
    HopNextKey1 = { fg = p.cyan, bold = true },
    HopNextKey2 = { fg = p.cyan_dim },
    HopUnmatched = { fg = p.gray1 },
    HopCursor = { reverse = true },
    HopPreview = { fg = p.g2, bg = p.bg3 },

    -- lazy.nvim
    LazyNormal = { link = 'NormalFloat' },
    LazyH1 = { fg = p.black, bg = p.g0, bold = true },
    LazyH2 = { fg = p.g0, bold = true },
    LazyButton = { fg = p.gray4, bg = p.bg3 },
    LazyButtonActive = { fg = p.black, bg = p.g0, bold = true },
    LazySpecial = { fg = p.g0 },
    LazyProgressDone = { fg = p.g0 },
    LazyProgressTodo = { fg = p.gray1 },
    LazyCommit = { fg = p.gray3 },
    LazyCommitType = { fg = p.gray4 },
    LazyCommitIssue = { fg = p.gray3 },
    LazyCommitScope = { fg = p.gray4, italic = true },
    LazyDir = { fg = p.g0 },
    LazyUrl = { fg = p.g2, underline = true },
    LazyValue = { fg = p.g2 },
    LazyProp = { fg = p.gray3 },
    LazyComment = { link = 'Comment' },
    LazyDimmed = { fg = p.gray2 },
    LazyLocal = { fg = p.gray4 },
    LazyNoCond = { fg = p.yellow },
    LazyReasonCmd = { fg = p.gray4 },
    LazyReasonEvent = { fg = p.gray4 },
    LazyReasonFt = { fg = p.gray4 },
    LazyReasonImport = { fg = p.gray4 },
    LazyReasonKeys = { fg = p.gray4 },
    LazyReasonPlugin = { fg = p.gray4 },
    LazyReasonRequire = { fg = p.gray4 },
    LazyReasonRuntime = { fg = p.gray4 },
    LazyReasonSource = { fg = p.gray4 },
    LazyReasonStart = { fg = p.gray4 },
    LazyTaskOutput = { fg = p.gray3 },
    LazyTaskError = { fg = p.red },

    -- Mason
    MasonNormal = { link = 'NormalFloat' },
    MasonHeader = { fg = p.black, bg = p.g0, bold = true },
    MasonHeaderSecondary = { fg = p.black, bg = p.gray4, bold = true },
    MasonHeading = { fg = p.gray4, bold = true },
    MasonHighlight = { fg = p.g0 },
    MasonHighlightBlock = { fg = p.black, bg = p.g0 },
    MasonHighlightBlockBold = { fg = p.black, bg = p.g0, bold = true },
    MasonHighlightSecondary = { fg = p.gray4 },
    MasonHighlightBlockSecondary = { fg = p.black, bg = p.gray4 },
    MasonHighlightBlockBoldSecondary = { fg = p.black, bg = p.gray4, bold = true },
    MasonMuted = { fg = p.gray3 },
    MasonMutedBlock = { fg = p.gray4, bg = p.bg3 },
    MasonMutedBlockBold = { fg = p.gray4, bg = p.bg3, bold = true },
    MasonError = { fg = p.red },
    MasonWarning = { fg = p.orange },
    MasonLink = { fg = p.g2, underline = true },

    -- nvim-dap / dap-ui / virtual text
    DapUIScope = { fg = p.g0 },
    DapUIType = { fg = p.gray4 },
    DapUIValue = { fg = p.g1 },
    DapUIVariable = { fg = p.g1 },
    DapUIModifiedValue = { fg = p.orange, bold = true },
    DapUIDecoration = { fg = p.gray2 },
    DapUIThread = { fg = p.g0 },
    DapUIStoppedThread = { fg = p.cyan, bold = true },
    DapUIFrameName = { fg = p.g1 },
    DapUICurrentFrameName = { fg = p.cyan, bold = true },
    DapUISource = { fg = p.gray4 },
    DapUILineNumber = { fg = p.gray3 },
    DapUIFloatBorder = { link = 'FloatBorder' },
    DapUIWatchesEmpty = { fg = p.gray3 },
    DapUIWatchesValue = { fg = p.g0 },
    DapUIWatchesError = { fg = p.red },
    DapUIBreakpointsPath = { fg = p.g0 },
    DapUIBreakpointsInfo = { fg = p.gray3 },
    DapUIBreakpointsCurrentLine = { fg = p.cyan, bold = true },
    DapUIBreakpointsLine = { link = 'DapUILineNumber' },
    DapUIBreakpointsDisabledLine = { fg = p.gray1 },
    DapUIStepOver = { fg = p.gray4 },
    DapUIStepInto = { fg = p.gray4 },
    DapUIStepBack = { fg = p.gray4 },
    DapUIStepOut = { fg = p.gray4 },
    DapUIStop = { fg = p.red },
    DapUIPlayPause = { fg = p.g0 },
    DapUIRestart = { fg = p.g0 },
    DapUIUnavailable = { fg = p.gray1 },
    DapUIWinSelect = { fg = p.g0, bold = true },
    DapUIEndOfBuffer = { link = 'EndOfBuffer' },
    DapUIStepOverNC = { link = 'DapUIStepOver' },
    DapUIStepIntoNC = { link = 'DapUIStepInto' },
    DapUIStepBackNC = { link = 'DapUIStepBack' },
    DapUIStepOutNC = { link = 'DapUIStepOut' },
    DapUIStopNC = { link = 'DapUIStop' },
    DapUIPlayPauseNC = { link = 'DapUIPlayPause' },
    DapUIRestartNC = { link = 'DapUIRestart' },
    DapUIUnavailableNC = { link = 'DapUIUnavailable' },
    NvimDapVirtualText = { fg = p.gray2, italic = true },
    NvimDapVirtualTextChanged = { fg = p.orange, italic = true },
    NvimDapVirtualTextError = { fg = p.red_dim, italic = true },
    NvimDapVirtualTextInfo = { fg = p.gray2, italic = true },

    -- help / man / markdown (legacy syntax)
    helpHeader = { fg = p.g0, bold = true },
    helpHeadline = { fg = p.g0, bold = true },
    helpSectionDelim = { fg = p.gray2 },
    helpHyperTextJump = { fg = p.g0 },
    helpHyperTextEntry = { fg = p.g2 },
    helpCommand = { fg = p.gray4, bg = p.bg2 },
    helpExample = { fg = p.gray4 },
    helpOption = { fg = p.g2 },
    helpSpecial = { fg = p.g0 },
    manSectionHeading = { fg = p.g0, bold = true },
    manSubHeading = { fg = p.g2, bold = true },
    manOptionDesc = { fg = p.g2 },
    manReference = { fg = p.g0 },
    markdownCode = { fg = p.gray4 },
    markdownCodeBlock = { fg = p.gray4 },
    markdownHeadingDelimiter = { fg = p.g0 },
    markdownUrl = { fg = p.g2, underline = true },
  }

  for name, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, name, spec)
  end

  -- :terminal palette. Green ramp for the neutral slots; the remaining
  -- ANSI hues are desaturated so tool output stays quiet.
  local t = {
    [0] = p.bg4, p.red, p.g1, p.yellow, '#8aa4bf', '#b58fbf', p.cyan, p.g1,
    p.gray2, p.red, p.g0, p.yellow, '#a3b8cc', '#c9a8d1', p.cyan, p.g0,
  }
  for i = 0, 15 do
    vim.g['terminal_color_' .. i] = t[i]
  end
end

return M
